Adding enchant package in RHEL8 depedency
open-power-host-os/tests pull request #233
Opened 2020-10-27 07:02 UTC by spoorthy1303

Adding enchant package in RHEL8 depedency, It is required while installing Avocado on RHEL 8 
hence adding the package to RHEL list 

Signed-off by: Spoorthy<spoorthy@linux.vnet.ibm.com>

2020-11-04 04:13 UTC, sathnaga requested changes

2020-11-04 04:13 UTC, sathnaga commented on config/wrapper/env.conf
> +packages = gcc,python36-devel,xz-devel,python3-setuptools,numactl,policycoreutils-python-utils,openssl-devel,enchant
here we can avoid, as you have added in NV and phyp env...

2020-11-04 04:16 UTC, sathnaga requested changes
it has either to added in deps_rhel8 or respective leaf nodes, not needed to be placed in all levels,
lets keep it only on relevant places now, NV and phyp probably?

2020-11-30 07:14 UTC, spoorthy1303 commented
Addressed the review comments in commit c05e528

2020-11-30 13:46 UTC, PraveenPenguin commented
@spoorthy1303 please wrap both the commits in single commit

2020-12-01 05:10 UTC, sathnaga commented
@spoorthy1303  pls correct commit msg format.

```
Subject

Details

Signoff-by
```

E:g:- 
```
Author: Satheesh Rajendran <sathnaga@linux.vnet.ibm.com>
Date:   Wed Sep 2 12:29:59 2020 +0530

    Differentiate Pseries between Lpar and KVM guest
    
    Earlier we default pSeries to phyp environment, but
    that's not right, this patch differentiates Pseries
    between phyp Lpar and KVM guest.
    
    Signed-off-by: Satheesh Rajendran <sathnaga@linux.vnet.ibm.com>
```

2020-12-01 05:26 UTC, spoorthy1303 commented
Updated the commit message as per the review suggestion

2020-12-09 06:17 UTC, PraveenPenguin approved these changes

2020-12-09 06:49 UTC, sathnaga approved these changes

2020-12-09 06:50 UTC, merged