vNIC test bucket and common inputfile
open-power-host-os/tests pull request #241
Opened 2021-02-22 07:49 UTC by abdhaleegit

Added io_vnic.cfg and io_vnic_input.txt for vNIC functional test

Signed-off-by: Abdul Haleem <abdhalee@linux.vnet.ibm.com>

2021-02-24 14:10 UTC, narasimhan-v requested changes

2021-02-24 14:10 UTC, narasimhan-v commented on config/inputs/io_vnic_input.txt
> +sriov_adapters = "U78D8.ND0.FGD004S-P0-C6-C0 U78D8.ND0.FGD004S-P0-C6-C0"
@abdhaleegit Please remove these

2021-03-02 14:55 UTC, abdhaleegit commented
Job logs

```
[console-expect]#for test in $tests;do mkdir -p /home/ioci/logs/$test; python avocado-setup.py --run-suite host_$test --output-dir /home/ioci/logs/$test --no-deps-check --input-file /root/korg-zz3-lp3-input.txt;done
for test in $tests;do mkdir -p /home/ioci/logs/$test; python avocado-setup.py --run-suite host_$test --output-dir /home/ioci/logs/$test --no-deps-check --input-file /root/korg-zz3-lp3-input.txt;done
16:12:01 INFO    : Check for environment
16:12:01 INFO    : Creating temporary mux dir
16:12:22 INFO    : 
16:12:22 INFO    : Running Host Tests Suite io_vnic_network_virtualization_NetworkVirtualization_test_add_network_virtualization
16:12:22 INFO    : Running: /usr/local/bin/avocado run avocado-misc-tests/io/net/virt-net/network_virtualization.py:NetworkVirtualization.test_add$ -m /tmp/mux/io_vnic_network_virtualization_NetworkVirtualization_test_add_network_virtualization.yaml --force-job-id ebe3daf8bd3dd157b6488038aa51d700dbaa1208  --job-results-dir /home/ioci/logs/io_vnic/results
JOB ID     : ebe3daf8bd3dd157b6488038aa51d700dbaa1208
JOB LOG    : /home/ioci/logs/io_vnic/results/job-2021-02-11T16.12-ebe3daf/job.log
[  598.630604] device-mapper: uevent: version 1.0.3
[  598.630668] device-mapper: ioctl: 4.43.0-ioctl (2020-10-01) initialised: dm-devel@redhat.com
[  615.786597] ibmvnic 30000005: Partner initialization complete
[  615.786661] ibmvnic 30000005: Partner protocol version is 1
[  615.788202] ibmvnic 30000005: ibmvnic registered
[  615.788229] rpadlpar_io: slot U8375.42A.13C72EW-V3-C5 added
[  615.794443] ibmvnic 30000005 env5: renamed from eth0
[  616.211470] IPv6: ADDRCONF(NETDEV_CHANGE): env5: link becomes ready
 (1/1) avocado-misc-tests/io/net/virt-net/network_virtualization.py:NetworkVirtualization.test_add;run-1498:  PASS (18.56 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/ioci/logs/io_vnic/results/job-2021-02-11T16.12-ebe3daf/results.html
JOB TIME   : 19.61 s
16:13:20 INFO    : 
16:13:20 INFO    : 
16:13:20 INFO    : Running Host Tests Suite io_vnic_bonding_bonding_virtual
16:13:20 INFO    : Running: /usr/local/bin/avocado run avocado-misc-tests/io/net/bonding.py -m /tmp/mux/io_vnic_bonding_bonding_virtual.yaml --force-job-id 6e25e3fdcb6dc9950d7e640c01a8fcfdbfeb39d5  --job-results-dir /home/ioci/logs/io_vnic/results --execution-order tests-per-variant
JOB ID     : 6e25e3fdcb6dc9950d7e640c01a8fcfdbfeb39d5
JOB LOG    : /home/ioci/logs/io_vnic/results/job-2021-02-11T16.13-6e25e3f/job.log
 (1/6) avocado-misc-tests/io/net/bonding.py:Bonding.test_setup;run-Test-active-backup-41c1:  CANCEL: interface is not available (1.41 s)
 (2/6) avocado-misc-tests/io/net/bonding.py:Bonding.test_run;run-Test-active-backup-41c1:  CANCEL: interface is not available (1.42 s)
 (3/6) avocado-misc-tests/io/net/bonding.py:Bonding.test_cleanup;run-Test-active-backup-41c1:  CANCEL: interface is not available (1.33 s)
 (4/6) avocado-misc-tests/io/net/bonding.py:Bonding.test_setup;run-Test-802.3ad-875b:  CANCEL: interface is not available (1.31 s)
 (5/6) avocado-misc-tests/io/net/bonding.py:Bonding.test_run;run-Test-802.3ad-875b:  CANCEL: interface is not available (1.37 s)
 (6/6) avocado-misc-tests/io/net/bonding.py:Bonding.test_cleanup;run-Test-802.3ad-875b:  CANCEL: interface is not available (1.37 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 6
JOB HTML   : /home/ioci/logs/io_vnic/results/job-2021-02-11T16.13-6e25e3f/results.html
JOB TIME   : 9.13 s
16:14:05 INFO    : 
16:14:05 INFO    : 
16:14:05 INFO    : Running Host Tests Suite io_vnic_network_virtualization_NetworkVirtualization_test_backingdevadd_network_virtualization
16:14:05 INFO    : Running: /usr/local/bin/avocado run avocado-misc-tests/io/net/virt-net/network_virtualization.py:NetworkVirtualization.test_backingdevadd$ -m /tmp/mux/io_vnic_network_virtualization_NetworkVirtualization_test_backingdevadd_network_virtualization.yaml --force-job-id 32fdcd31773e6d31c192b226fde64b15b0a85090  --job-results-dir /home/ioci/logs/io_vnic/results
JOB ID     : 32fdcd31773e6d31c192b226fde64b15b0a85090
JOB LOG    : /home/ioci/logs/io_vnic/results/job-2021-02-11T16.14-32fdcd3/job.log
 (1/1) avocado-misc-tests/io/net/virt-net/network_virtualization.py:NetworkVirtualization.test_backingdevadd;run-1498:  PASS (18.03 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/ioci/logs/io_vnic/results/job-2021-02-11T16.14-32fdcd3/results.html
JOB TIME   : 18.72 s
16:15:00 INFO    : 
16:15:00 INFO    : 
16:15:00 INFO    : Running Host Tests Suite io_vnic_tcpdump_tcpdump-virt
16:15:00 INFO    : Running: /usr/local/bin/avocado run avocado-misc-tests/io/net/tcpdump.py -m /tmp/mux/io_vnic_tcpdump_tcpdump-virt.yaml --force-job-id 5ef6bed7e6ec8577b48fa08a691e8fe751454a86  --job-results-dir /home/ioci/logs/io_vnic/results --execution-order tests-per-variant
JOB ID     : 5ef6bed7e6ec8577b48fa08a691e8fe751454a86
JOB LOG    : /home/ioci/logs/io_vnic/results/job-2021-02-11T16.15-5ef6bed/job.log
 (01/14) avocado-misc-tests/io/net/tcpdump.py:TcpdumpTest.test;run-mtu-1500-mtu_timeout-options-generic-4637:  CANCEL: vnic1 interface is not available (0.57 s)
 (02/14) avocado-misc-tests/io/net/tcpdump.py:TcpdumpTest.test;run-mtu-9000-mtu_timeout-options-generic-288c:  CANCEL: vnic1 interface is not available (0.61 s)
 (03/14) avocado-misc-tests/io/net/tcpdump.py:TcpdumpTest.test;run-mtu-1500-mtu_timeout-options-generic_host-16bd:  CANCEL: vnic1 interface is not available (0.59 s)
 (04/14) avocado-misc-tests/io/net/tcpdump.py:TcpdumpTest.test;run-mtu-9000-mtu_timeout-options-generic_host-0956:  CANCEL: vnic1 interface is not available (0.57 s)
 (05/14) avocado-misc-tests/io/net/tcpdump.py:TcpdumpTest.test;run-mtu-1500-mtu_timeout-options-generic_src-1c58:  CANCEL: vnic1 interface is not available (0.63 s)
 (06/14) avocado-misc-tests/io/net/tcpdump.py:TcpdumpTest.test;run-mtu-9000-mtu_timeout-options-generic_src-14ab:  CANCEL: vnic1 interface is not available (0.59 s)
 (07/14) avocado-misc-tests/io/net/tcpdump.py:TcpdumpTest.test;run-mtu-1500-mtu_timeout-options-generic_dst-7af6:  CANCEL: vnic1 interface is not available (0.58 s)
 (08/14) avocado-misc-tests/io/net/tcpdump.py:TcpdumpTest.test;run-mtu-9000-mtu_timeout-options-generic_dst-796d:  CANCEL: vnic1 interface is not available (0.62 s)
 (09/14) avocado-misc-tests/io/net/tcpdump.py:TcpdumpTest.test;run-mtu-1500-mtu_timeout-options-protocol_tcp-2667:  CANCEL: vnic1 interface is not available (0.58 s)
 (10/14) avocado-misc-tests/io/net/tcpdump.py:TcpdumpTest.test;run-mtu-9000-mtu_timeout-options-protocol_tcp-26b5:  CANCEL: vnic1 interface is not available (0.65 s)
 (11/14) avocado-misc-tests/io/net/tcpdump.py:TcpdumpTest.test;run-mtu-1500-mtu_timeout-options-protocol_udp-34c1:  CANCEL: vnic1 interface is not available (0.54 s)
 (12/14) avocado-misc-tests/io/net/tcpdump.py:TcpdumpTest.test;run-mtu-9000-mtu_timeout-options-protocol_udp-c112:  CANCEL: vnic1 interface is not available (0.61 s)
 (13/14) avocado-misc-tests/io/net/tcpdump.py:TcpdumpTest.test;run-mtu-1500-mtu_timeout-options-protocol_icmp-7eae:  CANCEL: vnic1 interface is not available (0.57 s)
 (14/14) avocado-misc-tests/io/net/tcpdump.py:TcpdumpTest.test;run-mtu-9000-mtu_timeout-options-protocol_icmp-e4c6:  CANCEL: vnic1 interface is not available (0.64 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 14
JOB HTML   : /home/ioci/logs/io_vnic/results/job-2021-02-11T16.15-5ef6bed/results.html
JOB TIME   : 9.52 s
16:15:46 INFO    : 
16:15:46 INFO    : 
16:15:46 INFO    : Running Host Tests Suite io_vnic_bootlist_test_bootlist_test_network
16:15:46 INFO    : Running: /usr/local/bin/avocado run avocado-misc-tests/io/common/bootlist_test.py -m /tmp/mux/io_vnic_bootlist_test_bootlist_test_network.yaml --force-job-id 7db110215d65b521d447dff64bf01dc2242d9157  --job-results-dir /home/ioci/logs/io_vnic/results
JOB ID     : 7db110215d65b521d447d [...]

2021-03-02 14:57 UTC, abdhaleegit commented on config/inputs/io_vnic_input.txt
> +sriov_adapters = "U78D8.ND0.FGD004S-P0-C6-C0 U78D8.ND0.FGD004S-P0-C6-C0"
done

2021-03-11 04:27 UTC, narasimhan-v approved these changes

2021-03-11 04:27 UTC, merged